pipeline {
	agent any

	tools {
		maven 'maven3'
	}

	stages {
		stage('1. Diagnostic & Checkout') {
			steps {
				git branch: 'main', url: 'https://github.com/HajarHaoud/pipeline-spring.git'
				sh 'echo "--- Voici les fichiers à la racine du dépôt ---"'
				sh 'ls -F'
				sh 'echo "--- Vérification du dossier spring-pipeline ---"'
				sh 'ls -F spring-pipeline/ || echo "Le dossier spring-pipeline n\'existe pas à la racine"'
			}
		}

		stage('2. Build Maven') {
			steps {
				script {
					// On cherche dynamiquement où est le pom.xml
					if (fileExists('pom.xml')) {
						sh 'mvn clean package -DskipTests'
					} else if (fileExists('spring-pipeline/pom.xml')) {
						dir('spring-pipeline') {
							sh 'mvn clean package -DskipTests'
						}
					} else {
						error "Impossible de trouver le fichier pom.xml dans le projet !"
					}
				}
			}
		}

		stage('3. Build Docker') {
			steps {
				script {
					// On s'adapte aussi pour Docker
					def projectDir = fileExists('pom.xml') ? "." : "spring-pipeline"
					dir(projectDir) {
						withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
							sh "docker build -t hajarhaoud/spring-app:latest ."
							sh "echo $PASS | docker login -u $USER --password-stdin"
							sh "docker push hajarhaoud/spring-app:latest"
						}
					}
				}
			}
		}
	}
}