pipeline {
	agent any

	tools {
		maven 'maven3'
	}

	environment {
		DOCKER_USER = 'hajarhaoud'
		IMAGE_NAME = 'spring-app'
		IMAGE_TAG = "${env.BUILD_NUMBER}"
	}

	stages {

		stage('1. Diagnostic & Checkout') {
			steps {
				git branch: 'main', url: 'https://github.com/HajarHaoud/pipeline-spring.git'
				sh 'echo "--- Contenu du workspace après checkout ---"'
				sh 'pwd'
				sh 'ls -la'
			}
		}

		stage('2. Build Maven') {
			steps {
				sh 'mvn clean package -DskipTests'
				// PAS de dir('spring-pipeline') car il n'existe pas dans le repo GitHub
			}
		}

		stage('3. Build Docker') {
			steps {
				withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
					sh 'docker build -t hajarhaoud/spring-app:latest .'
					sh "echo $PASS | docker login -u $USER --password-stdin"
					sh 'docker push hajarhaoud/spring-app:latest'
				}
			}
		}

		stage('4. Deploy to K8s') {
			steps {
				// Si ton fichier deployment.yaml est AUSSI dans spring-pipeline
				dir('spring-pipeline') {
					withCredentials([file(credentialsId: 'k8s-config', variable: 'KUBECONFIG')]) {
						sh "kubectl --kubeconfig=${KUBECONFIG} apply -f deployment.yaml"
						sh "kubectl --kubeconfig=${KUBECONFIG} rollout restart deployment/spring-app"
					}
				}
			}
		}
	}
}